project_id = "tallersoftware-467001"
location     = "us-central1"
backend_image = "us-central1-docker.pkg.dev/tallersoftware-467001/bakery-tallersoftware/backend:latest"
frontend_image = "us-central1-docker.pkg.dev/tallersoftware-467001/bakery-tallersoftware/frontend:latest"
db_user     = "postgres"
db_password = "miclave123"
db_name     = "bakerydb"
db_instance_connection_name = "/cloudsql/tallersoftware-467001:us-central1:postgres-instance"

network_name = "projects/tallersoftware-467001/global/networks/my-vpc"